-- Create Database
CREATE DATABASE CX_146_DAY6;
-- Use Database
USE CX_146_DAY6;


-- Create table Employee 
CREATE TABLE Employees (
    EmployeeID INT PRIMARY KEY IDENTITY(1,1),
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50),
    Department VARCHAR(50),
    Salary DECIMAL(10, 2)
);


INSERT INTO Employees (FirstName, LastName, Department, Salary)
VALUES
('Alice', 'Smith', 'HR', 60000),
('Bob', 'Johnson', 'IT', 80000),
('Charlie', 'Lee', 'Finance', 70000),
('David', 'Kim', 'HR', 50000),
('Eva', 'Williams', 'IT', 90000),
('Frank', 'Brown', 'Marketing', 65000),
('Grace', 'Davis', 'Finance', 72000),
('Helen', 'Taylor', 'Marketing', 75000);


SELECT * FROM Employees;


/*
Triggers
Syntax
CREATE TRIGGER TriggerName ON Table AFTER INSERT|UPDATE|DELETE AS BEGIN ... END
Use
Automatically perform actions after an event.

Send an alert when a new employee is added.

*/

-- DEFINING TRIGGER FOR INSERT OPERATION

CREATE TRIGGER TRG_NEWEMP ON EMPLOYEES
AFTER INSERT AS
BEGIN
       PRINT ' A NEW EMPLOYEE HAS JOINED';
END;


INSERT INTO Employees (FirstName, LastName, Department, Salary)
VALUES
('ASHOK', 'SHARMA', 'HR', 65000);


-- Display Employee Records

SELECT * FROM Employees;



-- DEFINE TRIGGER MAINTAINING LOG/ AUDIT TABLE

CREATE TABLE EMPLOG(
LOGID INT PRIMARY KEY IDENTITY(1,1),
MESSAGE NVARCHAR(255),
CREATEDAT DATETIME DEFAULT GETDATE()
);


CREATE TRIGGER TRG_EMP ON EMPLOYEES
AFTER INSERT AS
BEGIN
      INSERT INTO EMPLOG (MESSAGE) VALUES (' A NEW EMPLOYEE IS ADDED');
END;


SELECT * FROM EMPLOG;

INSERT INTO Employees (FirstName, LastName, Department, Salary)
VALUES
('KIRAN', 'YADAV', 'IT', 85000);


-- Update Trigger

CREATE TRIGGER TRG_UPDATEEMPLOYEE ON EMPLOYEES
AFTER UPDATE AS
BEGIN
    INSERT INTO EMPLOG (MESSAGE) VALUES ('EMPLOYEE RECORD IS UPDATED');

END;

-- Update existing record
UPDATE Employees
SET Salary=88000 WHERE FIRSTNAME='KIRAN';

SELECT * FROM Employees;

SELECT * FROM EMPLOG;

/*
CTE (Common Table Expression)
Syntax
	WITH CTEName AS (SELECT ...)
	SELECT * FROM CTEName;
Use
Temporary named result set for easier querying.
Use Case
Easily find high earning employees.

*/
select * from Employees;
-- display record of employees having salary greater than 800000

select * from Employees
where salary>80000;

WITH HIGHEARNERS AS 
(select * from Employees where salary>80000)
SELECT * FROM HIGHEARNERS;




-- CTE to count employees per department and filter only those departments with more than 2 employee

-- DISPLAY EMPLOYEE DETAILS DEPARTMENT WISE

SELECT DEPARTMENT,COUNT(*) AS CNT FROM Employees
GROUP BY DEPARTMENT;

WITH DEPTCOUNT AS (
SELECT DEPARTMENT,COUNT(*) AS CNT FROM Employees
GROUP BY DEPARTMENT)
SELECT E.FIRSTNAME,E.LASTNAME,E.DEPARTMENT,E.Salary FROM Employees E
JOIN DEPTCOUNT D
ON E.Department=D.Department
WHERE D.CNT>2;



WITH ITSTAFF AS (
SELECT * FROM EMPLOYEES WHERE Department='IT')
SELECT * FROM ITSTAFF WHERE Salary>80000;



-- PROVIDE RANK TO EMPL BASED ON SALARY
/*
select columnname,fun()
over([partition by clause],
           [order by clause]);  */

WITH RANKEDEMP AS (
SELECT EMPLOYEEID,FIRSTNAME,LASTNAME,SALARY,DENSE_RANK()
OVER(ORDER BY SALARY DESC) AS SALARYRANK
FROM EMPLOYEES)
SELECT * FROM RANKEDEMP WHERE SALARYRANK <=3;

SELECT * FROM Employees;

-- TCL (Transaction Control Language)


-- BY DEFAULT DML QUERIES ARE AUTO COMMIT

-- Here Begin transaction is used without commit 
BEGIN TRANSACTION
INSERT INTO Employees(FirstName, LastName, Department, Salary)
VALUES
('ABC', 'XYZ', 'FINANCE', 95000);

SELECT * FROM Employees;

-- roll back the transaction
BEGIN TRANSACTION
ROLLBACK TRANSACTION;

SELECT * FROM Employees;



BEGIN TRANSACTION
INSERT INTO Employees (FirstName, LastName, Department, Salary)
VALUES
('PQR', 'LMN', 'IT', 75000);

UPDATE Employees
SET FirstName='ALICIA' WHERE EmployeeID=1;

DELETE FROM Employees
WHERE EmployeeID=5;


BEGIN TRANSACTION
ROLLBACK TRANSACTION;

SELECT * FROM Employees;


-- savepoint : creating temporary memory for storing values

BEGIN TRANSACTION
INSERT INTO Employees (FirstName, LastName, Department, Salary) VALUES ('LEENA', 'BHAGWAT', 'HR', 85000);
SAVE TRANSACTION OCT12
INSERT INTO Employees (FirstName, LastName, Department, Salary)
VALUES ('GRACE', 'SHARMA', 'FINANCE', 95000);

-- ROLL BACK TO PREVIOUS 

SELECT * FROM Employees;

BEGIN TRANSACTION
ROLLBACK TRANSACTION OCT12;

SELECT * FROM Employees;

BEGIN TRANSACTION
ROLLBACK TRANSACTION;


SELECT * FROM Employees;


BEGIN TRANSACTION
COMMIT
UPDATE Employees
SET Department='MARKETING' WHERE EmployeeID=9;



-- IMPORT SALES_DATA_700 CSV FILE

select * from sales;


-- add new column
ALTER TABLE SALES
ADD AMOUNT FLOAT;

SELECT * FROM SALES;

ALTER TABLE SALES
ALTER COLUMN UNITS_SOLD FLOAT;

ALTER TABLE SALES
ALTER COLUMN UNIT_PRICE FLOAT;

-- UPDATE COLUMN AMOUNT (UNIT_PRICE*UNITS_SOLD)

UPDATE SALES
SET AMOUNT= UNITS_SOLD * UNIT_PRICE;

SELECT * FROM SALES;

-- DESCRIPTIVE ANALYSIS  (STATISTICAL ANALYSIS)

-- COUNT OF RECORDS/ROWS

SELECT COUNT(*) AS CNT FROM SALES;
 -- 700 ROWS
 
 -- TOTAL REVENUE GENERATED

 SELECT SUM(AMOUNT) AS TOTALREVENUE FROM SALES;

 -- TOTAL REVENUE = RS 698715

 -- PRODUCT WISE REVENUE

  SELECT PRODUCT, SUM(AMOUNT) AS TOTALREVENUE FROM SALES
  GROUP BY PRODUCT;

  /* PRODUCT	TOTALREVENUE
Biscuits	45900
Bread	53500
Butter	61695
Cheese	102780
*/

 SELECT PRODUCT, SUM(AMOUNT) AS TOTALREVENUE FROM SALES
  GROUP BY PRODUCT
  ORDER BY TOTALREVENUE DESC;

  /*
  PRODUCT	TOTALREVENUE
Oil	148500
Cheese	102780
Rice	83100
  */

-- TOP 1 PRODUCT BASED ON REVENUE
 SELECT TOP (1) PRODUCT, SUM(AMOUNT) AS TOTALREVENUE FROM SALES
  GROUP BY PRODUCT
  ORDER BY TOTALREVENUE DESC;
  
  --  PRODUCT	TOTALREVENUE
  --  Oil	148500

-- BOTTOM 3 PRODUCTS BASED ON REVENUE
 SELECT TOP (3) PRODUCT, SUM(AMOUNT) AS TOTALREVENUE FROM SALES
  GROUP BY PRODUCT
  ORDER BY TOTALREVENUE ASC;

  -- TOTAL NUMBER OF PRODUCTS SOLD
  SELECT SUM(UNITS_SOLD) AS TOTALPRODUCTSOLD FROM SALES;
  -- 17778 

  -- PRODUCT WISE QUANTITY

    SELECT PRODUCT,SUM(UNITS_SOLD) AS TOTALPRODUCTSOLD FROM SALES
	GROUP BY PRODUCT;

-- TOP 5 PRODUCTS QUANTITY WISE

   SELECT TOP(5) PRODUCT,SUM(UNITS_SOLD) AS TOTALPRODUCTSOLD FROM SALES
	GROUP BY PRODUCT
	ORDER BY  TOTALPRODUCTSOLD DESC;

/*
  PRODUCT	TOTALPRODUCTSOLD
Biscuits	2295
Bread	2140
Eggs	1847
Juice	1805
Sugar	1754
*/

-- TIME BASED ANALYSIS

SELECT * FROM SALES;

-- ADD NEW COLUMN SALEMONTH

ALTER TABLE SALES
ADD SALEMONTH INT;

UPDATE SALES
SET SALEMONTH=MONTH(DATE);

ALTER TABLE SALES
ADD SALEMONTHNAME VARCHAR(50);

UPDATE SALES
SET SALEMONTHNAME= DATENAME(month,date);


SELECT * FROM SALES;

-- MONTH WISE SALES ANALYSIS

SELECT SALEMONTHNAME,SUM(AMOUNT) AS MONTHLYREVENUE FROM SALES
GROUP BY SALEMONTHNAME
ORDER BY MONTHLYREVENUE DESC;

/*
SALEMONTHNAME	MONTHLYREVENUE
March	125540
April	122035
May	121375
June	116910
January	106605
February	106250

*/

select DATENAME(month,date) as monthname from sales;



